name: mini_wallet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_secure_storage: ^10.0.0
  get: ^4.7.3
  get_storage: ^2.1.1
  intl: ^0.20.2
  path: ^1.9.1
  toastification: ^3.2.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/env/
    - assets/fonts/Inter/
    - assets/fonts/Manrope/
    - assets/fonts/Noto_Sans_Khmer/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter/Inter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter/Inter-BlackItalic.ttf
          weight: 900
          style: italic

    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/Noto_Sans_Khmer/NotoSansKhmer-Thin.ttf
          weight: 100
        - asset: assets/fonts/Noto_Sans_Khmer/NotoSansKhmer-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans_Khmer/NotoSansKhmer-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans_Khmer/NotoSansKhmer-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_Khmer/NotoSansKhmer-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans_Khmer/NotoSansKhmer-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans_Khmer/NotoSansKhmer-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans_Khmer/NotoSansKhmer-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans_Khmer/NotoSansKhmer-Black.ttf
          weight: 900
